spring:
  application:
    name: noq-backend

  jpa:
    hibernate:
      naming:
        # This enables auto conversion of Camel Casing Model Properties to Snake Case DB Columns
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PWD:postgres}
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: admin
#    password: admin
    hikari:
      connection-timeout: 30000
      idleTimeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      pool-name: "noq-hikari-conn-pool"
    driver-class-name: org.postgresql.Driver

  jmx:
    enabled: false

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
